
CREATE TABLE [SysUser]
(
	UserId UNIQUEIDENTIFIER PRIMARY KEY,
	UserName NVARCHAR(50) ,
	[Password] CHAR(32),
	LoginNo VARCHAR(25), 

	UpdateUser UNIQUEIDENTIFIER,
	CreateUser UNIQUEIDENTIFIER,
	 CreateDate DATETIME,
	UpdateDate DATETIME
)
GO
CREATE TABLE [SysRole]
(
	RoleId UNIQUEIDENTIFIER PRIMARY KEY,
	RoleCode NVARCHAR(50) ,
	RoleName CHAR(32),
	LoginNo VARCHAR(25), 

	UpdateUser UNIQUEIDENTIFIER,
	CreateUser UNIQUEIDENTIFIER,
	CreateDate DATETIME,
	UpdateDate DATETIME
)
GO
CREATE TABLE [SysMenu]
(
	MenuId UNIQUEIDENTIFIER PRIMARY KEY,
	ParentId UNIQUEIDENTIFIER,
	MenuCode VARCHAR(25),
	MenuName NVARCHAR(25),
	ActionUrl VARCHAR(25),

	UpdateUser UNIQUEIDENTIFIER,
	CreateUser UNIQUEIDENTIFIER,
	CreateDate DATETIME,
	UpdateDate DATETIME
)